// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __demo_h__
#define __demo_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Demo
{

class Operator;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Demo::Operator>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Demo::Operator*);

}

}

namespace Demo
{

class Operator;
bool operator==(const Operator&, const Operator&);
bool operator<(const Operator&, const Operator&);
::Ice::Object* upCast(::Demo::Operator*);
typedef ::IceInternal::Handle< ::Demo::Operator> OperatorPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Demo::Operator> OperatorPrx;
void __patch(OperatorPtr&, const ::Ice::ObjectPtr&);

}

namespace Demo
{

class Callback_Operator_check_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Operator_check_Base> Callback_Operator_checkPtr;

class Callback_Operator_isprimary_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Operator_isprimary_Base> Callback_Operator_isprimaryPtr;

class Callback_Operator_setprimary_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Operator_setprimary_Base> Callback_Operator_setprimaryPtr;

class Callback_Operator_sendpackage_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Operator_sendpackage_Base> Callback_Operator_sendpackagePtr;

class Callback_Operator_log_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Operator_log_Base> Callback_Operator_logPtr;

}

namespace IceProxy
{

namespace Demo
{

class Operator : virtual public ::IceProxy::Ice::Object
{
public:

    bool check()
    {
        return check(0);
    }
    bool check(const ::Ice::Context& __ctx)
    {
        return check(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_check(const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_check(0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_check(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_check(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_check(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_check(&__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_check(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_check(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_check(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (bool)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Demo::OperatorPrx __proxy = ::Demo::OperatorPrx::uncheckedCast(__result->getProxy());
                bool __ret;
                try
                {
                    __ret = __proxy->end_check(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (bool)> _response;
        };
        return begin_check(__ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_check()
    {
        return begin_check(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_check(const ::Ice::Context& __ctx)
    {
        return begin_check(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_check(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_check(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_check(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_check(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_check(const ::Demo::Callback_Operator_checkPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_check(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_check(const ::Ice::Context& __ctx, const ::Demo::Callback_Operator_checkPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_check(&__ctx, __del, __cookie);
    }

    bool end_check(const ::Ice::AsyncResultPtr&);
    
private:

    bool check(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_check(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    bool isprimary()
    {
        return isprimary(0);
    }
    bool isprimary(const ::Ice::Context& __ctx)
    {
        return isprimary(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_isprimary(const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_isprimary(0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_isprimary(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_isprimary(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_isprimary(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_isprimary(&__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_isprimary(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_isprimary(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_isprimary(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (bool)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Demo::OperatorPrx __proxy = ::Demo::OperatorPrx::uncheckedCast(__result->getProxy());
                bool __ret;
                try
                {
                    __ret = __proxy->end_isprimary(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (bool)> _response;
        };
        return begin_isprimary(__ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_isprimary()
    {
        return begin_isprimary(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_isprimary(const ::Ice::Context& __ctx)
    {
        return begin_isprimary(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_isprimary(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_isprimary(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_isprimary(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_isprimary(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_isprimary(const ::Demo::Callback_Operator_isprimaryPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_isprimary(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_isprimary(const ::Ice::Context& __ctx, const ::Demo::Callback_Operator_isprimaryPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_isprimary(&__ctx, __del, __cookie);
    }

    bool end_isprimary(const ::Ice::AsyncResultPtr&);
    
private:

    bool isprimary(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_isprimary(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void setprimary()
    {
        setprimary(0);
    }
    void setprimary(const ::Ice::Context& __ctx)
    {
        setprimary(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_setprimary(const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_setprimary(0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_setprimary(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_setprimary(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_setprimary(const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_setprimary(&__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_setprimary(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_setprimary(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_setprimary()
    {
        return begin_setprimary(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setprimary(const ::Ice::Context& __ctx)
    {
        return begin_setprimary(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setprimary(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setprimary(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setprimary(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setprimary(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setprimary(const ::Demo::Callback_Operator_setprimaryPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setprimary(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setprimary(const ::Ice::Context& __ctx, const ::Demo::Callback_Operator_setprimaryPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setprimary(&__ctx, __del, __cookie);
    }

    void end_setprimary(const ::Ice::AsyncResultPtr&);
    
private:

    void setprimary(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setprimary(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void sendpackage()
    {
        sendpackage(0);
    }
    void sendpackage(const ::Ice::Context& __ctx)
    {
        sendpackage(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_sendpackage(const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_sendpackage(0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_sendpackage(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_sendpackage(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_sendpackage(const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_sendpackage(&__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_sendpackage(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_sendpackage(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_sendpackage()
    {
        return begin_sendpackage(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendpackage(const ::Ice::Context& __ctx)
    {
        return begin_sendpackage(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendpackage(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendpackage(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendpackage(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendpackage(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendpackage(const ::Demo::Callback_Operator_sendpackagePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendpackage(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendpackage(const ::Ice::Context& __ctx, const ::Demo::Callback_Operator_sendpackagePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendpackage(&__ctx, __del, __cookie);
    }

    void end_sendpackage(const ::Ice::AsyncResultPtr&);
    
private:

    void sendpackage(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_sendpackage(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void log()
    {
        log(0);
    }
    void log(const ::Ice::Context& __ctx)
    {
        log(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_log(const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_log(0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_log(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_log(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_log(const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_log(&__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_log(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_log(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_log()
    {
        return begin_log(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_log(const ::Ice::Context& __ctx)
    {
        return begin_log(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_log(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_log(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_log(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_log(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_log(const ::Demo::Callback_Operator_logPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_log(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_log(const ::Ice::Context& __ctx, const ::Demo::Callback_Operator_logPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_log(&__ctx, __del, __cookie);
    }

    void end_log(const ::Ice::AsyncResultPtr&);
    
private:

    void log(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_log(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Operator> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_secure(bool __secure) const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_twoway() const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_oneway() const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_batchOneway() const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_datagram() const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_batchDatagram() const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_compress(bool __compress) const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Operator> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Operator*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace Demo
{

class Operator : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual bool check(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual bool isprimary(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void setprimary(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void sendpackage(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void log(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace Demo
{

class Operator : virtual public ::IceDelegate::Demo::Operator,
                 virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual bool check(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool isprimary(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void setprimary(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void sendpackage(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void log(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace Demo
{

class Operator : virtual public ::IceDelegate::Demo::Operator,
                 virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual bool check(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool isprimary(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void setprimary(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void sendpackage(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void log(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace Demo
{

class Operator : virtual public ::Ice::Object
{
public:

    typedef OperatorPrx ProxyType;
    typedef OperatorPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual bool check(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___check(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool isprimary(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___isprimary(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setprimary(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setprimary(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void sendpackage(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___sendpackage(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void log(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___log(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const Operator& l, const Operator& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Operator& l, const Operator& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Demo
{

template<class T>
class CallbackNC_Operator_check : public Callback_Operator_check_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_Operator_check(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::OperatorPrx __proxy = ::Demo::OperatorPrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_check(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_Operator_checkPtr
newCallback_Operator_check(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_check<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Operator_checkPtr
newCallback_Operator_check(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_check<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Operator_check : public Callback_Operator_check_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_Operator_check(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::OperatorPrx __proxy = ::Demo::OperatorPrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_check(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Operator_checkPtr
newCallback_Operator_check(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_check<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Operator_checkPtr
newCallback_Operator_check(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_check<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Operator_isprimary : public Callback_Operator_isprimary_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_Operator_isprimary(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::OperatorPrx __proxy = ::Demo::OperatorPrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_isprimary(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_Operator_isprimaryPtr
newCallback_Operator_isprimary(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_isprimary<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Operator_isprimaryPtr
newCallback_Operator_isprimary(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_isprimary<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Operator_isprimary : public Callback_Operator_isprimary_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_Operator_isprimary(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::OperatorPrx __proxy = ::Demo::OperatorPrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_isprimary(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Operator_isprimaryPtr
newCallback_Operator_isprimary(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_isprimary<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Operator_isprimaryPtr
newCallback_Operator_isprimary(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_isprimary<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Operator_setprimary : public Callback_Operator_setprimary_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Operator_setprimary(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Operator_setprimaryPtr
newCallback_Operator_setprimary(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_setprimary<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Operator_setprimaryPtr
newCallback_Operator_setprimary(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_setprimary<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Operator_setprimaryPtr
newCallback_Operator_setprimary(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_setprimary<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Operator_setprimaryPtr
newCallback_Operator_setprimary(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_setprimary<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Operator_setprimary : public Callback_Operator_setprimary_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Operator_setprimary(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Operator_setprimaryPtr
newCallback_Operator_setprimary(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_setprimary<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Operator_setprimaryPtr
newCallback_Operator_setprimary(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_setprimary<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Operator_setprimaryPtr
newCallback_Operator_setprimary(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_setprimary<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Operator_setprimaryPtr
newCallback_Operator_setprimary(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_setprimary<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Operator_sendpackage : public Callback_Operator_sendpackage_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Operator_sendpackage(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Operator_sendpackagePtr
newCallback_Operator_sendpackage(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_sendpackage<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Operator_sendpackagePtr
newCallback_Operator_sendpackage(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_sendpackage<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Operator_sendpackagePtr
newCallback_Operator_sendpackage(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_sendpackage<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Operator_sendpackagePtr
newCallback_Operator_sendpackage(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_sendpackage<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Operator_sendpackage : public Callback_Operator_sendpackage_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Operator_sendpackage(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Operator_sendpackagePtr
newCallback_Operator_sendpackage(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_sendpackage<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Operator_sendpackagePtr
newCallback_Operator_sendpackage(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_sendpackage<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Operator_sendpackagePtr
newCallback_Operator_sendpackage(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_sendpackage<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Operator_sendpackagePtr
newCallback_Operator_sendpackage(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_sendpackage<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Operator_log : public Callback_Operator_log_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Operator_log(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Operator_logPtr
newCallback_Operator_log(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_log<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Operator_logPtr
newCallback_Operator_log(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_log<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Operator_logPtr
newCallback_Operator_log(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_log<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Operator_logPtr
newCallback_Operator_log(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Operator_log<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Operator_log : public Callback_Operator_log_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Operator_log(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Operator_logPtr
newCallback_Operator_log(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_log<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Operator_logPtr
newCallback_Operator_log(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_log<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Operator_logPtr
newCallback_Operator_log(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_log<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Operator_logPtr
newCallback_Operator_log(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Operator_log<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
